# Generated by Django 4.1.7 on 2023-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(blank=True, default=89888880900),
        ),
    ]
