# Generated by Django 4.1.7 on 2023-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='site_id',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
    ]
