# Generated by Django 4.1.7 on 2023-05-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_activation_key_alter_user_site_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_someUser', models.IntegerField()),
                ('someData', models.CharField(max_length=255)),
            ],
        ),
    ]
